---
version: '3.6'
services:
  drs:
    container_name: pa-drs
    build:
      context: .
    links:
    - db
    ports:
    - "8080:8080"
    environment:
    - MONGO_URI=mongodb://admin:password@db:27017/drsStore?authSource=admin
    - STORAGE_SECURE=true
    # These are secret so to ensure they don't get checked into source
    # control they are read in from the same environment variable from 
    # the users shell before running docker-compose up. See README for 
    # more details on running this.
    - PUB_KEY
    - SEC_KEY
    - STORAGE_HOST
    - STORAGE_BUCKET
    - ACCESS_KEY
    - SECRET_KEY
  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"
