---
version: '3.6'
services:
  drs:
    container_name: pa-drs
    build:
      context: .
    links:
    - db
    ports:
    - "8080:8080"
    environment:
      MONGO_URI: "mongodb://admin:password@db:27017/drsStore?authSource=admin"
      #PUBKEY_PATH: /tmp/pubkey
      #SECKEY_PATH: /tmp/seckey
      STORAGE_HOST: s3.au-southeast-1.amazonaws.com
      STORAGE_BUCKET: mybucket
      STORAGE_SECURE: true
      ACCESS_KEY: key
      SECRET_KEY: secret
  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"
