version: '3.6'
services:

    drs:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        links: 
            - mongodb
            - minio
        command: bash -c "cd /app/drs_filer; python app.py"
        ports:
            - "8080:8080"
        volumes:
            - appdata:/app

    mongodb: 
        image: mongo:3.6
        container_name: pa-mongo-db
        restart: unless-stopped
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"


    minio:
        image: quay.io/minio/minio
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "9090:9090"
        env_file: .env
        volumes:
            - miniodata:/data
        command: server /data --console-address ":9090"




volumes:
    appdata:

    mongodata:

    miniodata:

    
