---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
