name: Integration tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and bring up the stack
      run: docker compose up -d
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MONGO_URI: mongodb://admin:password@db:27017/drsStore?authSource=admin
        STORAGE_HOST: ${{ vars.STORAGE_HOST }}
        STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
        SEC_KEY: |
          -----BEGIN CRYPT4GH PRIVATE KEY-----
          YzRnaC12MQAEbm9uZQAEbm9uZQAg5eYgf1QUl1cFyquP6OgMz2faF2uSc4s8OXf0L4MLRQM=
          -----END CRYPT4GH PRIVATE KEY-----
        PUB_KEY: |
          -----BEGIN CRYPT4GH PUBLIC KEY-----
          dq/9iq2WMYpYQqnxVpfd0pwRp2PToAccVWldr+kynCI=
          -----END CRYPT4GH PUBLIC KEY-----
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Update base dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install test dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-test.txt
        python -m pip install git+https://github.com/PacificAnalytics/pa-DRS-Crypt4GH-Client#subdirectory=crypt4gh-common
        python -m pip install git+https://github.com/PacificAnalytics/pa-DRS-Crypt4GH-Client#subdirectory=drs-client  
    - name: Test
      run: python -m pytest integration/
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DRS_HOST: ${{ vars.DRS_HOST }}
        STORAGE_HOST: ${{ vars.STORAGE_HOST }}
        STORAGE_BUCKET: ${{ vars.STORAGE_BUCKET }}
