name: Integration tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: cp integration/env.txt .env
    - name: Build and bring up the stack
      run: docker compose up -d
    - name: Configure Minio
      run: ./configure-minio.sh
    - name: Setup minio host mapping
      run: |
        sudo echo "127.0.0.1 minio" | sudo tee -a /etc/hosts
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Update base dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install test dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-test.txt
    - name: Test
      run: python -m pytest integration/
