name: Integration tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Create env file
    #   run: cp integration/env.txt .env
    # - name: Build and bring up the stack
    #   run: docker compose up -d
    # - name: Install the Minio client
    #   run: |
    #     curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc
    #     chmod +x $HOME/minio-binaries/mc
    #     echo "PATH=${PATH}:${HOME}/minio-binaries/" >> "$GITHUB_ENV"
    # - name: Configure Minio
    #   run: ./configure-minio.sh
    # - name: Setup minio host mapping
    #   run: |
    #     sudo echo "127.0.0.1 minio" | sudo tee -a /etc/hosts
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: "3.10"
    # - name: Update base dependencies
    #   run: python -m pip install --upgrade pip setuptools wheel
    # - name: Install test dependencies
    #   run: |
    #     python -m pip install -r requirements.txt
    #     python -m pip install -r requirements-test.txt
    # - name: Install DRS uploader
    #   run: |
    #     python -m pip install -e uploader/ -v
    - name: Install DRS client
      run: |
        pip install git+https://gboris:${PA_DRS_CRYPT4GH_DOWNLOADER_TOKEN}@github.com/PacificAnalytics/pa-DRS-Crypt4GH-Downloader.git
    # - name: Test
    #   run: python -m pytest integration/
