name: Tests

on:
  pull_request

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update base dependencies
      run: python -m pip install --upgrade pip setuptools wheel
    - name: Install package
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-test.txt
        python -m pip install . -v
    - name: Run linter
      run: python -m flake8 .
    - name: Run DRS-filer tests
      run: python -m pytest --cov=drs_filer tests/
